export const siteConfig = {
  name: "Mnnan - Frontend Developer & WordPress Specialist",
  description: "Professional portfolio of Mnnan, a skilled Frontend Developer & WordPress Specialist. Expert in React, Next.js, and modern web technologies. View my projects and get in touch for collaboration.",
  url: "https://my-portfolio-nu-two-55.vercel.app",
  ogImage: "/assets/images/profile-image-mnnan.jpg",
  links: {
    github: "https://github.com/mnnandev",
    linkedin: "https://linkedin.com/in/mnnandev",
  },
  keywords: [
    "Frontend Developer",
    "React Developer",
    "Next.js Developer",
    "WordPress Developer",
    "Web Developer",
    "UI/UX Developer",
    "JavaScript Developer",
    "Portfolio",
    "Mnnan",
    "Web Development",
    "Responsive Design",
    "Modern Web Technologies",
    "Custom WordPress Development",
    "React Applications",
    "Next.js Applications",
    "Tailwind CSS",
    "Web Performance",
    "SEO Optimization",
    "Mobile-First Development",
    "Full Stack Developer",
    "Web Application Development",
    "Progressive Web Apps",
    "Frontend Architecture",
    "Web Accessibility",
    "Performance Optimization"
  ],
  author: "Mnnan",
  twitter: "@mnnandev",
};

export const defaultMetadata = {
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  keywords: siteConfig.keywords,
  authors: [{ name: siteConfig.author }],
  creator: siteConfig.author,
  publisher: siteConfig.author,
  links: siteConfig.links,
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: "Mnnan - Frontend Developer & WordPress Specialist Portfolio",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: siteConfig.twitter,
    site: siteConfig.twitter,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  alternates: {
    canonical: siteConfig.url,
  },
  verification: {
    google: "googlecf1e47c80a57ab84", // Google Search Console verification code
  },
  category: "technology",
  classification: "Portfolio",
  referrer: "origin-when-cross-origin",
  metadataBase: new URL(siteConfig.url),
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
}; 